version: '3'

services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome-debug
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5900:5900
    depends_on:
      - hub
  nodejs:
    build: .
    environment:
      - "TZ=Japan"
    volumes:
      - .:/app
      - node_modules_volume:/app/node_modules
volumes:
  node_modules_volume:
